package phalangee.view;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.*;
import javax.swing.text.Highlighter.HighlightPainter;


public class GUILogin extends javax.swing.JFrame{
	
	private static GUILogin loginInstance;
	private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton CreateAccountBtn;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel MPBP;
    private javax.swing.JSeparator MPLblSep;
    private javax.swing.JPanel MPLbls;
    private javax.swing.JPanel MPMPInputs;
    private javax.swing.JSeparator MPMPSep1;
    private javax.swing.JSeparator MPMPSep2;
    private javax.swing.JPanel MPRP;
    private javax.swing.JPanel MPTP;
    private javax.swing.JPanel MiddlePanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JSeparator TPBPSep;
    private javax.swing.JSeparator TPTPSep;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLbl;
    
	/**
     * Creates new form GUIUserLogin
     */
    public GUILogin() {
        initComponents();
    }
    
    public static GUILogin getInstance() {
		if(loginInstance == null) {
			loginInstance = new GUILogin();
		}
		return loginInstance;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        TPTPSep = new javax.swing.JSeparator();
        CreateAccountBtn = new javax.swing.JButton();
        TPBPSep = new javax.swing.JSeparator();
        RightPanel = new javax.swing.JPanel();
        BottomPanel = new javax.swing.JPanel();
        MiddlePanel = new javax.swing.JPanel();
        MPLbls = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        MPLblSep = new javax.swing.JSeparator();
        passwordLbl = new javax.swing.JLabel();
        MPTP = new javax.swing.JPanel();
        MPRP = new javax.swing.JPanel();
        MPBP = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        MPMPInputs = new javax.swing.JPanel();
        usernameInput = new javax.swing.JTextField();
        MPMPSep1 = new javax.swing.JSeparator();
        passwordInput = new javax.swing.JPasswordField();
        MPMPSep2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        LeftPanel.setPreferredSize(new java.awt.Dimension(30, 120));

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        getContentPane().add(LeftPanel, java.awt.BorderLayout.LINE_START);

        TopPanel.setPreferredSize(new java.awt.Dimension(400, 50));
        TopPanel.setLayout(new javax.swing.BoxLayout(TopPanel, javax.swing.BoxLayout.Y_AXIS));
        TopPanel.add(TPTPSep);

        CreateAccountBtn.setText("Create Account");
        CreateAccountBtn.setAlignmentX(0.55F);
        TopPanel.add(CreateAccountBtn);

        TPBPSep.setOrientation(javax.swing.SwingConstants.VERTICAL);
        TPBPSep.setMaximumSize(new java.awt.Dimension(0, 32767));
        TPBPSep.setMinimumSize(new java.awt.Dimension(0, 10));
        TPBPSep.setPreferredSize(new java.awt.Dimension(0, 10));
        TopPanel.add(TPBPSep);

        getContentPane().add(TopPanel, java.awt.BorderLayout.PAGE_START);

        RightPanel.setPreferredSize(new java.awt.Dimension(30, 120));

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        getContentPane().add(RightPanel, java.awt.BorderLayout.LINE_END);

        BottomPanel.setPreferredSize(new java.awt.Dimension(400, 20));

        javax.swing.GroupLayout BottomPanelLayout = new javax.swing.GroupLayout(BottomPanel);
        BottomPanel.setLayout(BottomPanelLayout);
        BottomPanelLayout.setHorizontalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        BottomPanelLayout.setVerticalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(BottomPanel, java.awt.BorderLayout.PAGE_END);

        MiddlePanel.setMaximumSize(new java.awt.Dimension(600, 500));
        MiddlePanel.setMinimumSize(new java.awt.Dimension(200, 50));
        MiddlePanel.setName(""); // NOI18N
        MiddlePanel.setPreferredSize(new java.awt.Dimension(340, 50));
        MiddlePanel.setLayout(new java.awt.BorderLayout());

        MPLbls.setMaximumSize(new java.awt.Dimension(120, 300));
        MPLbls.setPreferredSize(new java.awt.Dimension(130, 50));
        MPLbls.setLayout(new javax.swing.BoxLayout(MPLbls, javax.swing.BoxLayout.Y_AXIS));

        usernameLbl.setText("Username:");
        usernameLbl.setAlignmentX(0.5F);
        usernameLbl.setIconTextGap(50);
        MPLbls.add(usernameLbl);

        MPLblSep.setOrientation(javax.swing.SwingConstants.VERTICAL);
        MPLblSep.setMaximumSize(new java.awt.Dimension(0, 40));
        MPLblSep.setMinimumSize(new java.awt.Dimension(0, 5));
        MPLblSep.setPreferredSize(new java.awt.Dimension(0, 20));
        MPLbls.add(MPLblSep);

        passwordLbl.setText("Password:");
        passwordLbl.setAlignmentX(0.5F);
        passwordLbl.setIconTextGap(20);
        MPLbls.add(passwordLbl);

        MiddlePanel.add(MPLbls, java.awt.BorderLayout.LINE_START);

        MPTP.setMaximumSize(new java.awt.Dimension(300, 300));
        MPTP.setMinimumSize(new java.awt.Dimension(149, 100));
        MPTP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));
        MiddlePanel.add(MPTP, java.awt.BorderLayout.PAGE_START);

        MPRP.setMinimumSize(new java.awt.Dimension(10, 60));
        MPRP.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout MPRPLayout = new javax.swing.GroupLayout(MPRP);
        MPRP.setLayout(MPRPLayout);
        MPRPLayout.setHorizontalGroup(
            MPRPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        MPRPLayout.setVerticalGroup(
            MPRPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        MiddlePanel.add(MPRP, java.awt.BorderLayout.LINE_END);

        MPBP.setMaximumSize(new java.awt.Dimension(0, 70));
        MPBP.setPreferredSize(new java.awt.Dimension(340, 70));
        MPBP.setLayout(new javax.swing.BoxLayout(MPBP, javax.swing.BoxLayout.Y_AXIS));

        loginBtn.setText("Login");
        loginBtn.setAlignmentX(0.5F);
        loginBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MPBP.add(loginBtn);

        MiddlePanel.add(MPBP, java.awt.BorderLayout.PAGE_END);

        MPMPInputs.setPreferredSize(new java.awt.Dimension(140, 50));
        MPMPInputs.setLayout(new javax.swing.BoxLayout(MPMPInputs, javax.swing.BoxLayout.Y_AXIS));

        usernameInput.setMargin(new java.awt.Insets(0, 6, 2, 6));
        usernameInput.setMaximumSize(new java.awt.Dimension(200, 300));
        usernameInput.setMinimumSize(new java.awt.Dimension(64, 24));
        usernameInput.setPreferredSize(new java.awt.Dimension(130, 30));
        MPMPInputs.add(usernameInput);

        MPMPSep1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        MPMPSep1.setMaximumSize(new java.awt.Dimension(0, 400));
        MPMPSep1.setPreferredSize(new java.awt.Dimension(0, 30));
        MPMPInputs.add(MPMPSep1);

        passwordInput.setMaximumSize(new java.awt.Dimension(200, 300));
        passwordInput.setPreferredSize(new java.awt.Dimension(90, 30));
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        MPMPInputs.add(passwordInput);

        MPMPSep2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        MPMPSep2.setMaximumSize(new java.awt.Dimension(0, 500));
        MPMPSep2.setPreferredSize(new java.awt.Dimension(0, 40));
        MPMPInputs.add(MPMPSep2);

        MiddlePanel.add(MPMPInputs, java.awt.BorderLayout.CENTER);

        getContentPane().add(MiddlePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>   
	
    
    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    } 
}
